"""
Trains two models:
1. crop_model.pkl        -> recommends best crop from soil/climate features
2. disease_risk_model.pkl -> predicts disease risk (Low/Medium/High) given
                              soil/climate features + chosen crop

Also saves:
- scaler.pkl        (StandardScaler fit on numeric features)
- crop_encoder.pkl   (LabelEncoder for crop <-> disease risk model's crop input)
- risk_encoder.pkl   (LabelEncoder for Low/Medium/High labels)
- feature_importance.json (for the explainability section on the result page)
- model_metrics.json (accuracy/F1 for both models, shown in report/demo)

Run: python train_model.py
"""

import json   # Used to serialize feature importances and model metrics to JSON files
import joblib # Used to save (serialize) trained ML models and preprocessors to disk as .pkl files
import numpy as np   # Numerical array operations (used implicitly by sklearn)
import pandas as pd  # Data loading and manipulation (reading CSV, DataFrames)
from sklearn.ensemble import RandomForestClassifier  # Ensemble ML classifier used for both models
from sklearn.preprocessing import StandardScaler, LabelEncoder  # Scaling features & encoding labels
from sklearn.model_selection import train_test_split  # Splits data into training and test sets
from sklearn.metrics import accuracy_score, f1_score, classification_report  # Model evaluation metrics

# Load the synthetic dataset generated by generate_dataset.py.
# The CSV contains columns: nitrogen, phosphorus, potassium, temperature,
# humidity, ph, rainfall, crop, disease_risk
df = pd.read_csv("dataset.csv")

# Define the 7 numeric input features that both models will use.
# These represent soil nutrients (N, P, K) and environmental conditions
# (temperature, humidity, pH, rainfall).
NUMERIC_FEATURES = ["nitrogen", "phosphorus", "potassium", "temperature", "humidity", "ph", "rainfall"]

# =====================================================================
# MODEL 1: Crop recommendation (features -> crop)
# This model takes soil/climate readings and recommends the best crop
# to grow under those conditions.
# =====================================================================

# X1 = feature matrix: only the 7 numeric columns (no crop or disease_risk)
X1 = df[NUMERIC_FEATURES]
# y1 = target variable: which crop to recommend
y1 = df["crop"]

# StandardScaler normalizes features to zero mean and unit variance.
# This is important for many ML algorithms to perform well, ensuring
# no single feature dominates due to its scale (e.g., rainfall in mm vs pH).
scaler = StandardScaler()
# fit_transform() computes mean/std from training data AND transforms it
X1_scaled = scaler.fit_transform(X1)

# Split the data: 80% training, 20% testing.
# random_state=42 ensures reproducibility (same split every run).
# stratify=y1 ensures each crop class is proportionally represented
# in both train and test sets (important for imbalanced classes).
X1_train, X1_test, y1_train, y1_test = train_test_split(
    X1_scaled, y1, test_size=0.2, random_state=42, stratify=y1
)

# RandomForestClassifier: an ensemble of decision trees.
# n_estimators=200: build 200 decision trees and vote on the final prediction.
# max_depth=12: limit tree depth to prevent overfitting (each tree can only
# make 12 splits deep).
# random_state=42: reproducibility for the random tree-building process.
crop_model = RandomForestClassifier(n_estimators=200, max_depth=12, random_state=42)
# Train the crop recommendation model on the training data
crop_model.fit(X1_train, y1_train)

# Make predictions on the held-out test set to evaluate performance
y1_pred = crop_model.predict(X1_test)
# Calculate accuracy: percentage of correct predictions
crop_acc = accuracy_score(y1_test, y1_pred)
# Calculate weighted F1 score: harmonic mean of precision and recall,
# weighted by class frequency (good for imbalanced datasets)
crop_f1 = f1_score(y1_test, y1_pred, average="weighted")
# Print the accuracy score to console
print("Crop model accuracy:", crop_acc)
# Print a detailed classification report with precision, recall, F1 per class
print(classification_report(y1_test, y1_pred))

# =====================================================================
# MODEL 2: Disease risk prediction (features + crop -> risk)
# This model predicts whether conditions are Low, Medium, or High risk
# for crop disease, given both the numeric features AND the specific crop.
# =====================================================================

# LabelEncoder converts text labels (crop names) to integers.
# e.g., "cotton" -> 0, "maize" -> 1, "rice" -> 2, etc.
crop_encoder = LabelEncoder()
# Add a new column with the encoded (numeric) crop values
df["crop_encoded"] = crop_encoder.fit_transform(df["crop"])

# X2 = features: the 7 numeric features PLUS the encoded crop
# Including the crop is important because disease risk depends on
# which crop is being grown (e.g., rice in wet conditions vs millet)
X2 = df[NUMERIC_FEATURES + ["crop_encoded"]]
# y2 = target: disease risk level (Low, Medium, or High)
y2 = df["disease_risk"]

# A separate scaler for Model 2 because the feature set is different
# (8 features instead of 7, since crop_encoded is included).
# We need separate scalers because scaling is fitted per feature set.
scaler2 = StandardScaler()
X2_scaled = scaler2.fit_transform(X2)

# Encode the risk labels: High/Low/Medium -> 0/1/2 (alphabetical order)
# This is needed because RandomForestClassifier works with numbers, not strings.
risk_encoder = LabelEncoder()
y2_encoded = risk_encoder.fit_transform(y2)  # High/Low/Medium -> 0/1/2 alphabetically

# Same 80/20 split with stratification for the risk model
X2_train, X2_test, y2_train, y2_test = train_test_split(
    X2_scaled, y2_encoded, test_size=0.2, random_state=42, stratify=y2_encoded
)

# RandomForestClassifier with slightly shallower trees (max_depth=10)
# since disease risk prediction may be more prone to overfitting
risk_model = RandomForestClassifier(n_estimators=200, max_depth=10, random_state=42)
risk_model.fit(X2_train, y2_train)

# Evaluate the disease risk model on the test set
y2_pred = risk_model.predict(X2_test)
risk_acc = accuracy_score(y2_test, y2_pred)
risk_f1 = f1_score(y2_test, y2_pred, average="weighted")
print("\nDisease risk model accuracy:", risk_acc)
# Print classification report with class names (Low/Medium/High) shown
print(classification_report(y2_test, y2_pred, target_names=risk_encoder.classes_))

# =====================================================================
# Save all trained artifacts to disk for use by the Django web app.
# These .pkl files are loaded at runtime by predictor/ml/predict.py.
# =====================================================================

# Save the trained crop recommendation model
joblib.dump(crop_model, "crop_model.pkl")
# Save the trained disease risk model
joblib.dump(risk_model, "disease_risk_model.pkl")
# Save the scaler fitted on the 7-feature crop model input
joblib.dump(scaler, "scaler_crop.pkl")
# Save the scaler fitted on the 8-feature risk model input
joblib.dump(scaler2, "scaler_risk.pkl")
# Save the LabelEncoder that maps crop names to integers
joblib.dump(crop_encoder, "crop_encoder.pkl")
# Save the LabelEncoder that maps risk levels (Low/Medium/High) to integers
joblib.dump(risk_encoder, "risk_encoder.pkl")

# Create a dictionary mapping feature names to their importance scores.
# Feature importance in Random Forest = how much each feature contributes
# to reducing impurity across all trees. Higher = more influential.
feature_importance = {
    "crop_model": dict(zip(NUMERIC_FEATURES, crop_model.feature_importances_.tolist())),
    "risk_model": dict(zip(NUMERIC_FEATURES + ["crop"], risk_model.feature_importances_.tolist())),
}
# Save to JSON so the web app can display which features matter most
with open("feature_importance.json", "w") as f:
    json.dump(feature_importance, f, indent=2)

# Save accuracy and F1 scores for both models to JSON
# This is used for display in the web app's report/demo page
metrics = {
    "crop_model": {"accuracy": crop_acc, "f1_weighted": crop_f1},
    "disease_risk_model": {"accuracy": risk_acc, "f1_weighted": risk_f1},
}
with open("model_metrics.json", "w") as f:
    json.dump(metrics, f, indent=2)

print("\nAll model artifacts saved.")
